[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.5"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_NODE_VERSION = "18.20.5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
